insert into Division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'Lower');
insert into Division (name, capital, region) values ('Bago Region', 'Bago', 'Lower');
insert into Division (name, capital, region) values ('Chin State', 'Hakha', 'West');
insert into Division (name, capital, region) values ('Kachin State', 'Myitkyina', 'North');
insert into Division (name, capital, region) values ('Kayah State', 'Loikaw', 'East');
insert into Division (name, capital, region) values ('Kayin State', 'Pa-an', 'South');
insert into Division (name, capital, region) values ('Magway Region', 'Magwe', 'Central');
insert into Division (name, capital, region) values ('Mandalay Region', 'Mandalay', 'Central');
insert into Division (name, capital, region) values ('Mon State', 'Mawlamyine', 'South');
insert into Division (name, capital, region) values ('Rakhine State', 'Sittwe', 'West');
insert into Division (name, capital, region) values ('Shan State', 'Taunggyi', 'East');
insert into Division (name, capital, region) values ('Sagaing Region', 'Sagaing', 'North');
insert into Division (name, capital, region) values ('Tanintharyi Region', 'Dawei', 'South');
insert into Division (name, capital, region) values ('Yangon Region', 'Yangon', 'Lower');
insert into Division (name, capital, region) values ('Naypyidaw Union Territory', 'Naypyidaw', 'Central');

insert into township (division_id, name) values (1, 'Hinthada');
insert into township (division_id, name) values (1, 'Lemyethna');
insert into township (division_id, name) values (1, 'Zalun');
insert into township (division_id, name) values (1, 'Ithapyu');
insert into township (division_id, name) values (1, 'Labutta');
insert into township (division_id, name) values (1, 'Mawlamyinegyun');
insert into township (division_id, name) values (1, 'Kyonmanage');
insert into township (division_id, name) values (1, 'Pyinsalu');
insert into township (division_id, name) values (1, 'Danubyu');
insert into township (division_id, name) values (1, 'Ma-ubin');
insert into township (division_id, name) values (1, 'Nyaungdon');
insert into township (division_id, name) values (1, 'Pantanaw');
insert into township (division_id, name) values (1, 'Einme');
insert into township (division_id, name) values (1, 'Myaungmya');
insert into township (division_id, name) values (1, 'Wakema');
insert into township (division_id, name) values (1, 'Shwelaung');
insert into township (division_id, name) values (1, 'Kangyidaunk');
insert into township (division_id, name) values (1, 'Ngapudaw');
insert into township (division_id, name) values (1, 'Pathein');
insert into township (division_id, name) values (1, 'Thabaung');
insert into township (division_id, name) values (1, 'Chaungtha');
insert into township (division_id, name) values (1, 'Hainggyi');
insert into township (division_id, name) values (1, 'Ngayokekaung');
insert into township (division_id, name) values (1, 'Ngwesaung');
insert into township (division_id, name) values (1, 'Bogale');
insert into township (division_id, name) values (1, 'Dedaye');
insert into township (division_id, name) values (1, 'Kyaiklat');
insert into township (division_id, name) values (1, 'Pyapon');
insert into township (division_id, name) values (1, 'Ahmar');
insert into township (division_id, name) values (1, 'Kyaunggon');
insert into township (division_id, name) values (1, 'Kyonpyaw');
insert into township (division_id, name) values (1, 'Yekyi');
insert into township (division_id, name) values (1, 'Ahtaung');
insert into township (division_id, name) values (1, 'Ngathinechaung');
insert into township (division_id, name) values (1, 'Ingapu');
insert into township (division_id, name) values (1, 'Kyangin');
insert into township (division_id, name) values (1, 'Myanaung');
insert into township (division_id, name) values (1, 'Kanaung');

insert into township (division_id, name) values(2, 'Bago');
insert into township (division_id, name) values(2, 'Daik-U');
insert into township (division_id, name) values(2, 'Kawa');
insert into township (division_id, name) values(2, 'Nyaunglebin');
insert into township (division_id, name) values(2, 'Shwegyin');
insert into township (division_id, name) values(2, 'Thanatpin');
insert into township (division_id, name) values(2, 'Waw');
insert into township (division_id, name) values(2, 'Kyauktaga');
insert into township (division_id, name) values(2, 'Kyaukkyi');
insert into township (division_id, name) values(2, 'Oktwin');
insert into township (division_id, name) values(2, 'Pyu');
insert into township (division_id, name) values(2, 'Tantabin');
insert into township (division_id, name) values(2, 'Taungoo');
insert into township (division_id, name) values(2, 'Yedashe');
insert into township (division_id, name) values(2, 'Pandaung');
insert into township (division_id, name) values(2, 'Paukkaung');
insert into township (division_id, name) values(2, 'Paungde');
insert into township (division_id, name) values(2, 'Pyay');
insert into township (division_id, name) values(2, 'Shwedaung');
insert into township (division_id, name) values(2, 'Thegon');
insert into township (division_id, name) values(2, 'Gyobingauk');
insert into township (division_id, name) values(2, 'Letpadan');
insert into township (division_id, name) values(2, 'Minhla');
insert into township (division_id, name) values(2, 'Monyo');
insert into township (division_id, name) values(2, 'Okpho');
insert into township (division_id, name) values(2, 'Tharrawaddy');
insert into township (division_id, name) values(2, 'Nattalin');
insert into township (division_id, name) values(2, 'Zigon');

insert into township (division_id, name) values(3, 'Falam');
insert into township (division_id, name) values(3, 'Tiddim');
insert into township (division_id, name) values(3, 'Ton Zang');
insert into township (division_id, name) values(3, 'Hakha');
insert into township (division_id, name) values(3, 'Htantlang');
insert into township (division_id, name) values(3, 'Matupi');
insert into township (division_id, name) values(3, 'Paletwa');
insert into township (division_id, name) values(3, 'Kanpetlet');
insert into township (division_id, name) values(3, 'Mindat');

insert into township (division_id, name) values(4, 'Bhamo');
insert into township (division_id, name) values(4, 'Mansi');
insert into township (division_id, name) values(4, 'Momauk');
insert into township (division_id, name) values(4, 'Shwegu');
insert into township (division_id, name) values(4, 'Hpakant');
insert into township (division_id, name) values(4, 'Mogaung');
insert into township (division_id, name) values(4, 'Mohnyin');
insert into township (division_id, name) values(4, 'Chipwi');
insert into township (division_id, name) values(4, 'Hsawlaw');
insert into township (division_id, name) values(4, 'Injangyang');
insert into township (division_id, name) values(4, 'Myitkyina');
insert into township (division_id, name) values(4, 'Tanai');
insert into township (division_id, name) values(4, 'Waingmaw');
insert into township (division_id, name) values(4, 'Kawnglanghpu');
insert into township (division_id, name) values(4, 'Machanbaw');
insert into township (division_id, name) values(4, 'Nogmung');
insert into township (division_id, name) values(4, 'Putao');
insert into township (division_id, name) values(4, 'Sumprabum');

insert into township (division_id, name) values(5, 'Bawlakhe');
insert into township (division_id, name) values(5, 'Hpasawng');
insert into township (division_id, name) values(5, 'Mese');
insert into township (division_id, name) values(5, 'Ywathit Subtownship');
insert into township (division_id, name) values(5, 'Demoso');
insert into township (division_id, name) values(5, 'Hpruso');
insert into township (division_id, name) values(5, 'Loikaw');
insert into township (division_id, name) values(5, 'Shadaw');

insert into township (division_id, name) values(6, 'Hlaingbwe');
insert into township (division_id, name) values(6, 'Hpa-an');
insert into township (division_id, name) values(6, 'Thandaunggyi');
insert into township (division_id, name) values(6, 'Hpapun');
insert into township (division_id, name) values(6, 'Kawkareik');
insert into township (division_id, name) values(6, 'Kyain Seikgyi');
insert into township (division_id, name) values(6, 'Myawaddy');

insert into township (division_id, name) values(7, 'Gangaw');
insert into township (division_id, name) values(7, 'Saw');
insert into township (division_id, name) values(7, 'Htilin');
insert into township (division_id, name) values(7, 'Kyaukhtu');
insert into township (division_id, name) values(7, 'Chauk');
insert into township (division_id, name) values(7, 'Magway');
insert into township (division_id, name) values(7, 'Myothit');
insert into township (division_id, name) values(7, 'Natmauk');
insert into township (division_id, name) values(7, 'Taungdwingyi');
insert into township (division_id, name) values(7, 'Yenangyaung');
insert into township (division_id, name) values(7, 'Minbu');
insert into township (division_id, name) values(7, 'Ngape');
insert into township (division_id, name) values(7, 'Pwintbyu');
insert into township (division_id, name) values(7, 'Salin');
insert into township (division_id, name) values(7, 'Sidoktaya');
insert into township (division_id, name) values(7, 'Myaing');
insert into township (division_id, name) values(7, 'Pakokku');
insert into township (division_id, name) values(7, 'Pauk');
insert into township (division_id, name) values(7, 'Seikphyu');
insert into township (division_id, name) values(7, 'Yesagyo');
insert into township (division_id, name) values(7, 'Aunglan');
insert into township (division_id, name) values(7, 'Kamma');
insert into township (division_id, name) values(7, 'Mindon');
insert into township (division_id, name) values(7, 'Minhla');
insert into township (division_id, name) values(7, 'Sinbaungwe');
insert into township (division_id, name) values(7, 'Thayet');

insert into township (division_id, name) values(8, 'Kyaukse');
insert into township (division_id, name) values(8, 'Myittha');
insert into township (division_id, name) values(8, 'Sintgaing');
insert into township (division_id, name) values(8, 'Tada-U');
insert into township (division_id, name) values(8, 'Amarapura');
insert into township (division_id, name) values(8, 'Aungmyethazan');
insert into township (division_id, name) values(8, 'Chanayethazan');
insert into township (division_id, name) values(8, 'Chanmyathazi');
insert into township (division_id, name) values(8, 'Maha Aungmye');
insert into township (division_id, name) values(8, 'Patheingyi');
insert into township (division_id, name) values(8, 'Pyigyidagun');
insert into township (division_id, name) values(8, 'Mahlaing');
insert into township (division_id, name) values(8, 'Meiktila');
insert into township (division_id, name) values(8, 'Thazi');
insert into township (division_id, name) values(8, 'Wundwin');
insert into township (division_id, name) values(8, 'Myingyan');
insert into township (division_id, name) values(8, 'Natogyi');
insert into township (division_id, name) values(8, 'Ngazun');
insert into township (division_id, name) values(8, 'Taungtha');
insert into township (division_id, name) values(8, 'Kyaukpadaung');
insert into township (division_id, name) values(8, 'Nyaung-U');
insert into township (division_id, name) values(8, 'Ngathayauk Subtownship');
insert into township (division_id, name) values(8, 'Madaya');
insert into township (division_id, name) values(8, 'Mogok');
insert into township (division_id, name) values(8, 'Pyinoolwin');
insert into township (division_id, name) values(8, 'Singu');
insert into township (division_id, name) values(8, 'Thabeikkyin');
insert into township (division_id, name) values(8, 'Pyawbwe');
insert into township (division_id, name) values(8, 'Yamethi');

insert into township (division_id, name) values(9, 'Chaungzon');
insert into township (division_id, name) values(9, 'Kyaikmaraw');
insert into township (division_id, name) values(9, 'Mawlamyine');
insert into township (division_id, name) values(9, 'Mudon');
insert into township (division_id, name) values(9, 'Thanbyuzayat');
insert into township (division_id, name) values(9, 'Ye');
insert into township (division_id, name) values(9, 'Bilin');
insert into township (division_id, name) values(9, 'Kyaikto');
insert into township (division_id, name) values(9, 'Paung');
insert into township (division_id, name) values(9, 'Thaton');

insert into township (division_id, name) values(10, 'Ann');
insert into township (division_id, name) values(10, 'Kyaukpyu');
insert into township (division_id, name) values(10, 'Manaung');
insert into township (division_id, name) values(10, 'Ramree');
insert into township (division_id, name) values(10, 'Buthidaung');
insert into township (division_id, name) values(10, 'Maungdaw');
insert into township (division_id, name) values(10, 'Pauktaw');
insert into township (division_id, name) values(10, 'Ponnagyun');
insert into township (division_id, name) values(10, 'Rathedaung');
insert into township (division_id, name) values(10, 'Sittwe');
insert into township (division_id, name) values(10, 'Thandwe');
insert into township (division_id, name) values(10, 'Toungup');
insert into township (division_id, name) values(10, 'Gwa');
insert into township (division_id, name) values(10, 'Maei');
insert into township (division_id, name) values(10, 'Kyeintali');
insert into township (division_id, name) values(10, 'Kyauktaw');
insert into township (division_id, name) values(10, 'Minbya');
insert into township (division_id, name) values(10, 'Mrauk-U');
insert into township (division_id, name) values(10, 'Myebon');

insert into township (division_id, name) values(11, 'Kengtung');
insert into township (division_id, name) values(11, 'Mong Khet');
insert into township (division_id, name) values(11, 'Mong La (SR4)');
insert into township (division_id, name) values(11, 'Mong Yang');
insert into township (division_id, name) values(11, 'Mine Pauk');
insert into township (division_id, name) values(11, 'Minelar');
insert into township (division_id, name) values(11, 'Mong Hpayak (SR4)');
insert into township (division_id, name) values(11, 'Mong Yawng');
insert into township (division_id, name) values(11, 'Mineyu');
insert into township (division_id, name) values(11, 'Mong Hsat');
insert into township (division_id, name) values(11, 'Mong Ping');
insert into township (division_id, name) values(11, 'Mong Tong');
insert into township (division_id, name) values(11, 'Minekoke');
insert into township (division_id, name) values(11, 'Monehta');
insert into township (division_id, name) values(11, 'Ponparkyin');
insert into township (division_id, name) values(11, 'Tontar');
insert into township (division_id, name) values(11, 'Tachileik');
insert into township (division_id, name) values(11, 'Kyaing Lap (Kenglap)');
insert into township (division_id, name) values(11, 'Talay');
insert into township (division_id, name) values(11, 'Kunlong');
insert into township (division_id, name) values(11, 'Hsipaw');
insert into township (division_id, name) values(11, 'Kyaukme');
insert into township (division_id, name) values(11, 'Namtu');
insert into township (division_id, name) values(11, 'Nawnghkio');
insert into township (division_id, name) values(11, 'Minelon');
insert into township (division_id, name) values(11, 'Minengaw');
insert into township (division_id, name) values(11, 'Hseni');
insert into township (division_id, name) values(11, 'Lashio');
insert into township (division_id, name) values(11, 'Mongyai');
insert into township (division_id, name) values(11, 'Tangyan');
insert into township (division_id, name) values(11, 'Kutkai');
insert into township (division_id, name) values(11, 'Mu Se');
insert into township (division_id, name) values(11, 'Nanhkan');
insert into township (division_id, name) values(11, 'Manhero');
insert into township (division_id, name) values(11, 'Monekoe');
insert into township (division_id, name) values(11, 'Pansai (Kyu-kok)');
insert into township (division_id, name) values(11, 'Tamoenye');
insert into township (division_id, name) values(11, 'Mabein');
insert into township (division_id, name) values(11, 'Mongmit');
insert into township (division_id, name) values(11, 'Langhko');
insert into township (division_id, name) values(11, 'Mawkmai');
insert into township (division_id, name) values(11, 'Mong Nai');
insert into township (division_id, name) values(11, 'Mong Pan');
insert into township (division_id, name) values(11, 'Homane');
insert into township (division_id, name) values(11, 'Kengtaung');
insert into township (division_id, name) values(11, 'Kunhing');
insert into township (division_id, name) values(11, 'Kyethi');
insert into township (division_id, name) values(11, 'Lai-Hka');
insert into township (division_id, name) values(11, 'Loilen');
insert into township (division_id, name) values(11, 'Mong Hsu');
insert into township (division_id, name) values(11, 'Mong Kung');
insert into township (division_id, name) values(11, 'Nansang');
insert into township (division_id, name) values(11, 'Karli');
insert into township (division_id, name) values(11, 'Kholan');
insert into township (division_id, name) values(11, 'Minenaung');
insert into township (division_id, name) values(11, 'Minesan');
insert into township (division_id, name) values(11, 'Panglong');
insert into township (division_id, name) values(11, 'Kalaw');
insert into township (division_id, name) values(11, 'Lawksawk');
insert into township (division_id, name) values(11, 'Nyaungshwe');
insert into township (division_id, name) values(11, 'Pekon');
insert into township (division_id, name) values(11, 'Taunggyi');
insert into township (division_id, name) values(11, 'Indaw');
insert into township (division_id, name) values(11, 'Kyauktalongyi');
insert into township (division_id, name) values(11, 'Naungtayar');


insert into township (division_id, name) values(12, 'Hkamti (Singkaling Hkamti)');
insert into township (division_id, name) values(12, 'Homalin (Homalin)');
insert into township (division_id, name) values(12, 'Kanbalu (Kanbalu)');
insert into township (division_id, name) values(12, 'Kyunhla (Kyunhla)');
insert into township (division_id, name) values(12, 'Taze (Taze)');
insert into township (division_id, name) values(12, 'Ye-U (Ye-U)');
insert into township (division_id, name) values(12, 'Kale (Kalaymyo)');
insert into township (division_id, name) values(12, 'Kalewa (Kalewa)');
insert into township (division_id, name) values(12, 'Mingin (Mingin)');
insert into township (division_id, name) values(12, 'Banmauk (Banmauk)');
insert into township (division_id, name) values(12, 'Indaw (Indaw)');
insert into township (division_id, name) values(12, 'Katha (Katha)');
insert into township (division_id, name) values(12, 'Kawlin (Kawlin)');
insert into township (division_id, name) values(12, 'Pinlebu (Pinlebu)');
insert into township (division_id, name) values(12, 'Htigyaing (Htigyaing)');
insert into township (division_id, name) values(12, 'Wuntho (Wuntho)');
insert into township (division_id, name) values(12, 'Mawlaik (Mawlaik)');
insert into township (division_id, name) values(12, 'Paungbyin (Paungbyin)');
insert into township (division_id, name) values(12, 'Ayadaw (Ayadaw)');
insert into township (division_id, name) values(12, 'Budalin (Budalin)');
insert into township (division_id, name) values(12, 'Chaung-U (Chaung-U)');
insert into township (division_id, name) values(12, 'Monywa (Monywa)');
insert into township (division_id, name) values(12, 'Myaung (Myaung)');
insert into township (division_id, name) values(12, 'Myinmu (Myinmu)');
insert into township (division_id, name) values(12, 'Sagaing (Sagaing)');
insert into township (division_id, name) values(12, 'Khin-U (Khin-U)');
insert into township (division_id, name) values(12, 'Shwebo (Shwebo)');
insert into township (division_id, name) values(12, 'Wetlet (Wetlet)');
insert into township (division_id, name) values(12, 'Tabayin (Tabayin)');
insert into township (division_id, name) values(12, 'Tamu (Tamu)');
insert into township (division_id, name) values(12, 'Kani (Kani)');
insert into township (division_id, name) values(12, 'Pale (Pale)');
insert into township (division_id, name) values(12, 'Salingyi (Salingyi)');
insert into township (division_id, name) values(12, 'Yinmabin (Yinmabin)');

insert into township (division_id, name) values(13, 'Dawei');
insert into township (division_id, name) values(13, 'Launglon');
insert into township (division_id, name) values(13, 'Thayetchaung');
insert into township (division_id, name) values(13, 'Yebyu');
insert into township (division_id, name) values(13, 'Kaleinaung');
insert into township (division_id, name) values(13, 'Myitta');
insert into township (division_id, name) values(13, 'Bokpyin');
insert into township (division_id, name) values(13, 'Kawthaung');
insert into township (division_id, name) values(13, 'Karathuri');
insert into township (division_id, name) values(13, 'Khamaukgyi');
insert into township (division_id, name) values(13, 'Pyigyimandaing');
insert into township (division_id, name) values(13, 'Kyunsu');
insert into township (division_id, name) values(13, 'Myeik');
insert into township (division_id, name) values(13, 'Palaw');
insert into township (division_id, name) values(13, 'Tanintharyi');
insert into township (division_id, name) values(13, 'Palauk');

insert into township (division_id, name) values(14, 'Botataung');
insert into township (division_id, name) values(14, 'Dagon Seikkan');
insert into township (division_id, name) values(14, 'East Dagon');
insert into township (division_id, name) values(14, 'North Dagon');
insert into township (division_id, name) values(14, 'North Okkalapa');
insert into township (division_id, name) values(14, 'Pazundaung');
insert into township (division_id, name) values(14, 'South Dagon');
insert into township (division_id, name) values(14, 'South Okkalapa');
insert into township (division_id, name) values(14, 'Thingangyun');
insert into township (division_id, name) values(14, 'Dawbon1');
insert into township (division_id, name) values(14, 'Mingala Taungnyunt1');
insert into township (division_id, name) values(14, 'Tamwe1');
insert into township (division_id, name) values(14, 'Thaketa1');
insert into township (division_id, name) values(14, 'Yankin1');
insert into township (division_id, name) values(14, 'Hlaingthaya');
insert into township (division_id, name) values(14, 'Insein');
insert into township (division_id, name) values(14, 'Mingaladon');
insert into township (division_id, name) values(14, 'Shwepyitha');
insert into township (division_id, name) values(14, 'Hlegu');
insert into township (division_id, name) values(14, 'Hmawbi');
insert into township (division_id, name) values(14, 'Htantabin');
insert into township (division_id, name) values(14, 'Taikkyi');
insert into township (division_id, name) values(14, 'Dala');
insert into township (division_id, name) values(14, 'Seikkyi Kanaungto');
insert into township (division_id, name) values(14, 'Cocokyun');
insert into township (division_id, name) values(14, 'Kawhmu');
insert into township (division_id, name) values(14, 'Kayan');
insert into township (division_id, name) values(14, 'Kungyangon');
insert into township (division_id, name) values(14, 'Kyauktan');
insert into township (division_id, name) values(14, 'Thanlyin');
insert into township (division_id, name) values(14, 'Thongwa');
insert into township (division_id, name) values(14, 'Twante');
insert into township (division_id, name) values(14, 'Tada');
insert into township (division_id, name) values(14, 'Ahlon');
insert into township (division_id, name) values(14, 'Bahan');
insert into township (division_id, name) values(14, 'Dagon');
insert into township (division_id, name) values(14, 'Kyauktada');
insert into township (division_id, name) values(14, 'Kyimyindaing');
insert into township (division_id, name) values(14, 'Lanmadaw');
insert into township (division_id, name) values(14, 'Latha');
insert into township (division_id, name) values(14, 'Pabedan');
insert into township (division_id, name) values(14, 'Sanchaung');
insert into township (division_id, name) values(14, 'Seikkan');
insert into township (division_id, name) values(14, 'Hlaing');
insert into township (division_id, name) values(14, 'Kamayut');
insert into township (division_id, name) values(14, 'Mayangon');

insert into township (division_id, name) values(15, 'Ottarathiri');
insert into township (division_id, name) values(15, 'Pobbathiri');
insert into township (division_id, name) values(15, 'Tatkon');
insert into township (division_id, name) values(15, 'Zeyarthiri');
insert into township (division_id, name) values(15, 'Dekkhinathiri');
insert into township (division_id, name) values(15, 'Lewe');
insert into township (division_id, name) values(15, 'Pyinmana');
insert into township (division_id, name) values(15, 'Zabuthiri');

